# Generated by Django 4.0.1 on 2022-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0014_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='employee_app.Employee')),
            ],
        ),
    ]
