# Generated by Django 4.0.1 on 2022-01-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0017_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('company', 'first_name')},
        ),
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
