# Generated by Django 4.0.2 on 2022-02-25 05:07

import ExpensesTracker.main.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expense_image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), ExpensesTracker.main.validators.only_letters_validator])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), ExpensesTracker.main.validators.only_letters_validator])),
                ('budget', models.FloatField(default=0, validators=[ExpensesTracker.main.validators.below_zero_validator])),
                ('profile_image', models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='profile_pic', validators=[ExpensesTracker.main.validators.image_size_validator])),
            ],
        ),
    ]
