# Generated by Django 4.0.2 on 2022-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='id2',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='employees',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
