# Generated by Django 4.0.2 on 2022-02-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_testmodel_id2_testmodel_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='department',
            field=models.CharField(blank=True, default='1', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
