# Generated by Django 4.0.2 on 2022-02-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Do not show', 'Do not show')], default=('Do not show', 'Do not show'), max_length=11),
        ),
    ]
